---
# code: language=ansible
- name: Gather OS specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution_release }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - default.yml
  tags:
    - vars

- ansible.builtin.include_tasks: prepare.yml

- ansible.builtin.import_tasks: configure.yml

- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Enable Resilio Sync
  ansible.builtin.systemd:
    name: resilio-sync
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
