---
name: Integration
on:
  workflow_dispatch:
  push:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # first of each month
  #   - cron: '0 0 1 * *'

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian11
          - debian10
          - ubuntu2004
          - fedora35

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - uses: gofrolist/molecule-action@v2.4.0
