---
name: Integration
on:
  workflow_dispatch:
  push:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # first of each month
  #   - cron: '0 0 1 * *'

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian11
          - debian10
          - ubuntu2004
          - fedora35

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible-lint molecule[docker] pytest-testinfra yamllint

      - name: Run Molecule tests.
        run: molecule test -s default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
